<?php

/**
 * @author  Marco Daries, Alexander Langer (Source of ideas)
 * @copyright   2020-2024 Daries.dev
 * @license Daries.dev - Free License <https://daries.dev/en/license-for-free-plugins>
 */

use wcf\system\WCF;

$regions = [
    'Kreis Dithmarschen - Binnenland',
    'Kreis Dithmarschen - Küste',
    'Kreis Nordfriesland - Binnenland',
    'Kreis Nordfriesland - Küste',
    'Kreis Ostholstein - Binnenland',
    'Kreis Ostholstein - Küste',
    'Kreis Pinneberg',
    'Insel Helgoland',
    'Kreis Plön - Binnenland',
    'Kreis Plön - Küste',
    'Kreis Rendsburg-Eckernförde - Binnenland',
    'Kreis Rendsburg-Eckernförde - Küste',
    'Kreis Schleswig-Flensburg - Binnenland',
    'Kreis Schleswig-Flensburg - Küste',
    'Kreis Cuxhaven - Binnenland',
    'Kreis Cuxhaven - Küste',
    'Kreis Aurich - Binnenland',
    'Kreis Aurich - Küste',
    'Kreis Friesland - Binnenland',
    'Kreis Friesland - Küste',
    'Kreis Leer',
    'Insel Borkum',
    'Kreis und Stadt Oldenburg',
    'Kreis und Stadt Osnabrück',
    'Kreis Wesermarsch - Binnenland',
    'Kreis Wesermarsch - Küste',
    'Kreis Wittmund - Binnenland',
    'Kreis Wittmund - Küste',
    'Kreis Darmstadt-Dieburg und Stadt Darmstadt',
    'Kreis und Stadt Offenbach',
    'Kreis und Stadt Kassel',
    'Kreis Trier-Saarburg und Stadt Trier',
    'Kreis und Stadt Kaiserslautern',
    'Rhein-Pfalz-Kreis und Stadt Ludwigshafen',
    'Kreis Mainz-Bingen und Stadt Mainz',
    'Kreis Südwestpfalz und Stadt Pirmasens',
    'Kreis und Stadt Heilbronn',
    'Kreis und Stadt Karlsruhe',
    'Rhein-Neckar-Kreis und Stadt Heidelberg',
    'Enzkreis und Stadt Pforzheim',
    'Kreis Breisgau-Hochschwarzwald und Stadt Freiburg',
    'Alb-Donau-Kreis und Stadt Ulm',
    'Kreis und Stadt München',
    'Kreis und Stadt Rosenheim',
    'Kreis und Stadt Landshut',
    'Kreis und Stadt Passau',
    'Kreis Straubing-Bogen und Stadt Straubing',
    'Kreis und Stadt Regensburg',
    'Kreis und Stadt Bamberg',
    'Kreis und Stadt Bayreuth',
    'Kreis und Stadt Coburg',
    'Kreis und Stadt Hof',
    'Kreis und Stadt Ansbach',
    'Kreis und Stadt Fürth',
    'Kreis und Stadt Aschaffenburg',
    'Kreis und Stadt Schweinfurt',
    'Kreis und Stadt Würzburg',
    'Kreis und Stadt Augsburg',
    'Kreis Mecklenburgische Seenplatte - Nord',
    'Kreis Mecklenburgische Seenplatte - West',
    'Kreis Mecklenburgische Seenplatte - Südost',
    'Kreis Rostock - Binnenland Nord',
    'Kreis Rostock - Küste',
    'Kreis Rostock - Binnenland Süd',
    'Kreis Vorpommern-Rügen - Binnenland',
    'Kreis Vorpommern-Rügen - Küste',
    'Kreis Vorpommern-Rügen - Insel Rügen',
    'Kreis Nordwestmecklenburg - Binnenland',
    'Kreis Nordwestmecklenburg - Küste',
    'Kreis Vorpommern-Greifswald - Binnenland Nord',
    'Kreis Vorpommern-Greifswald - Küste Nord',
    'Kreis Vorpommern-Greifswald - Binnenland Süd',
    'Kreis Vorpommern-Greifswald - Küste Süd',
    'Kreis Ludwigslust-Parchim - West',
    'Kreis Ludwigslust-Parchim - Ost',
    'Kreis Mittelsachsen - Tiefland',
    'Kreis Mittelsachsen - Bergland',
    'Vogtlandkreis - Tiefland',
    'Vogtlandkreis - Bergland',
    'Kreis Zwickau - Tiefland',
    'Kreis Zwickau - Bergland',
    'Kreis Bautzen - Tiefland',
    'Kreis Bautzen - Bergland',
    'Kreis Görlitz - Tiefland',
    'Kreis Görlitz - Bergland',
    'Kreis Sächsische Schweiz-Osterzgebirge - Tiefland',
    'Kreis Sächsische Schweiz-Osterzgebirge - westelbisches Bergland',
    'Kreis Sächsische Schweiz-Osterzgebirge - ostelbisches Bergland',
    'Kreis Nordsachsen - Nord',
    'Kreis Nordsachsen - Süd',
    'Kreis Harz - Tiefland',
    'Kreis Harz - Bergland',
    'Stadt Flensburg',
    'Stadt Kiel',
    'Hansestadt Lübeck',
    'Stadt Neumünster',
    'Kreis Herzogtum Lauenburg',
    'Kreis Segeberg',
    'Kreis Steinburg',
    'Kreis Stormarn',
    'Hansestadt Hamburg',
    'Stadt Braunschweig',
    'Stadt Salzgitter',
    'Stadt Wolfsburg',
    'Kreis Gifhorn',
    'Kreis Goslar',
    'Kreis Helmstedt',
    'Kreis Northeim',
    'Kreis Peine',
    'Kreis Wolfenbüttel',
    'Kreis Göttingen',
    'Region Hannover',
    'Kreis Diepholz',
    'Kreis Hameln-Pyrmont',
    'Kreis Hildesheim',
    'Kreis Holzminden',
    'Kreis Nienburg',
    'Kreis Schaumburg',
    'Kreis Celle',
    'Kreis Harburg',
    'Kreis Lüchow-Dannenberg',
    'Kreis Lüneburg',
    'Kreis Osterholz',
    'Kreis Rotenburg (Wümme)',
    'Heidekreis',
    'Kreis Stade',
    'Kreis Uelzen',
    'Kreis Verden',
    'Stadt Delmenhorst',
    'Stadt Emden',
    'Stadt Wilhelmshaven',
    'Kreis Ammerland',
    'Kreis Cloppenburg',
    'Kreis Emsland',
    'Kreis Grafschaft Bentheim',
    'Kreis Vechta',
    'Hansestadt Bremen',
    'Stadt Bremerhaven',
    'Stadt Düsseldorf',
    'Stadt Duisburg',
    'Stadt Essen',
    'Stadt Krefeld',
    'Stadt Mönchengladbach',
    'Stadt Mülheim an der Ruhr',
    'Stadt Oberhausen',
    'Stadt Remscheid',
    'Stadt Solingen',
    'Stadt Wuppertal',
    'Kreis Kleve',
    'Kreis Mettmann',
    'Rhein-Kreis Neuss',
    'Kreis Viersen',
    'Kreis Wesel',
    'Bundesstadt Bonn',
    'Stadt Köln',
    'Stadt Leverkusen',
    'StädteRegion Aachen',
    'Kreis Düren',
    'Rhein-Erft-Kreis',
    'Kreis Euskirchen',
    'Kreis Heinsberg',
    'Oberbergischer Kreis',
    'Rheinisch-Bergischer Kreis',
    'Rhein-Sieg-Kreis',
    'Stadt Bottrop',
    'Stadt Gelsenkirchen',
    'Stadt Münster',
    'Kreis Borken',
    'Kreis Coesfeld',
    'Kreis Recklinghausen',
    'Kreis Steinfurt',
    'Kreis Warendorf',
    'Stadt Bielefeld',
    'Kreis Gütersloh',
    'Kreis Herford',
    'Kreis Höxter',
    'Kreis Lippe',
    'Kreis Minden-Lübbecke',
    'Kreis Paderborn',
    'Stadt Bochum',
    'Stadt Dortmund',
    'Stadt Hagen',
    'Stadt Hamm',
    'Stadt Herne',
    'Ennepe-Ruhr-Kreis',
    'Hochsauerlandkreis',
    'Märkischer Kreis',
    'Kreis Olpe',
    'Kreis Siegen-Wittgenstein',
    'Kreis Soest',
    'Kreis Unna',
    'Stadt Frankfurt am Main',
    'Stadt Wiesbaden',
    'Kreis Bergstraße',
    'Kreis Groß-Gerau',
    'Hochtaunuskreis',
    'Main-Kinzig-Kreis und Stadt Hanau',
    'Main-Taunus-Kreis',
    'Odenwaldkreis',
    'Rheingau-Taunus-Kreis',
    'Wetteraukreis',
    'Kreis Gießen',
    'Lahn-Dill-Kreis',
    'Kreis Limburg-Weilburg',
    'Kreis Marburg-Biedenkopf',
    'Vogelsbergkreis',
    'Kreis Fulda',
    'Kreis Hersfeld-Rotenburg',
    'Schwalm-Eder-Kreis',
    'Kreis Waldeck-Frankenberg',
    'Werra-Meissner-Kreis',
    'Stadt Koblenz',
    'Kreis Ahrweiler',
    'Kreis Altenkirchen',
    'Kreis Bad Kreuznach',
    'Kreis Birkenfeld',
    'Kreis Cochem-Zell',
    'Kreis Mayen-Koblenz',
    'Kreis Neuwied',
    'Rhein-Hunsrück-Kreis',
    'Rhein-Lahn-Kreis',
    'Westerwaldkreis',
    'Kreis Bernkastel-Wittlich',
    'Eifelkreis Bitburg-Prüm',
    'Kreis Vulkaneifel',
    'Stadt Frankenthal',
    'Stadt Landau in der Pfalz',
    'Stadt Neustadt an der Weinstraße',
    'Stadt Speyer',
    'Stadt Worms',
    'Stadt Zweibrücken',
    'Kreis Alzey-Worms',
    'Kreis Bad Dürkheim',
    'Donnersbergkreis',
    'Kreis Germersheim',
    'Kreis Kusel',
    'Kreis Südliche Weinstraße',
    'Stadt Stuttgart',
    'Kreis Böblingen',
    'Kreis Esslingen',
    'Kreis Göppingen',
    'Kreis Ludwigsburg',
    'Rems-Murr-Kreis',
    'Hohenlohekreis',
    'Kreis Schwäbisch Hall',
    'Main-Tauber-Kreis',
    'Kreis Heidenheim',
    'Ostalbkreis',
    'Stadt Baden-Baden',
    'Kreis Rastatt',
    'Stadt Mannheim',
    'Neckar-Odenwald-Kreis',
    'Kreis Calw',
    'Kreis Freudenstadt',
    'Kreis Emmendingen',
    'Ortenaukreis',
    'Kreis Rottweil',
    'Schwarzwald-Baar-Kreis',
    'Kreis Tuttlingen',
    'Kreis Konstanz',
    'Kreis Lörrach',
    'Kreis Waldshut',
    'Kreis Reutlingen',
    'Kreis Tübingen',
    'Zollernalbkreis',
    'Kreis Biberach',
    'Bodenseekreis',
    'Kreis Ravensburg',
    'Kreis Sigmaringen',
    'Stadt Ingolstadt',
    'Kreis Altötting',
    'Kreis Berchtesgadener Land',
    'Kreis Bad Tölz-Wolfratshausen',
    'Kreis Dachau',
    'Kreis Ebersberg',
    'Kreis Eichstätt',
    'Kreis Erding',
    'Kreis Freising',
    'Kreis Fürstenfeldbruck',
    'Kreis Garmisch-Partenkirchen',
    'Kreis Landsberg am Lech',
    'Kreis Miesbach',
    'Kreis Mühldorf a. Inn',
    'Kreis Neuburg-Schrobenhausen',
    'Kreis Pfaffenhofen a.d. Ilm',
    'Kreis Starnberg',
    'Kreis Traunstein',
    'Kreis Weilheim-Schongau',
    'Kreis Deggendorf',
    'Kreis Freyung-Grafenau',
    'Kreis Kelheim',
    'Kreis Regen',
    'Kreis Rottal-Inn',
    'Kreis Dingolfing-Landau',
    'Stadt Amberg',
    'Stadt Weiden in der Oberpfalz',
    'Kreis Amberg-Sulzbach',
    'Kreis Cham',
    'Kreis Neumarkt i.d. OPf.',
    'Kreis Neustadt a.d. Waldnaab',
    'Kreis Schwandorf',
    'Kreis Tirschenreuth',
    'Kreis Forchheim',
    'Kreis Kronach',
    'Kreis Kulmbach',
    'Kreis Lichtenfels',
    'Kreis Wunsiedel',
    'Stadt Erlangen',
    'Stadt Nürnberg',
    'Stadt Schwabach',
    'Kreis Erlangen-Höchstadt',
    'Kreis Nürnberger Land',
    'Kreis Neustadt a.d. Aisch - Bad Windsheim',
    'Kreis Roth',
    'Kreis Weißenburg-Gunzenhausen',
    'Kreis Bad Kissingen',
    'Kreis Rhön-Grabfeld',
    'Kreis Haßberge',
    'Kreis Kitzingen',
    'Kreis Miltenberg',
    'Kreis Main-Spessart',
    'Stadt Kaufbeuren',
    'Stadt Kempten (Allgäu)',
    'Stadt Memmingen',
    'Kreis Aichach-Friedberg',
    'Kreis Dillingen a.d. Donau',
    'Kreis Günzburg',
    'Kreis Neu-Ulm',
    'Kreis Lindau (Bodensee)',
    'Kreis Ostallgäu',
    'Kreis Unterallgäu',
    'Kreis Donau-Ries',
    'Kreis Oberallgäu',
    'Regionalverband Saarbrücken',
    'Kreis Merzig-Wadern',
    'Kreis Neunkirchen',
    'Kreis Saarlouis',
    'Saarpfalz-Kreis',
    'Kreis St. Wendel',
    'Berlin',
    'Stadt Brandenburg',
    'Stadt Cottbus',
    'Stadt Frankfurt (Oder)',
    'Stadt Potsdam',
    'Kreis Barnim',
    'Kreis Dahme-Spreewald',
    'Kreis Elbe-Elster',
    'Kreis Havelland',
    'Kreis Märkisch-Oderland',
    'Kreis Oberhavel',
    'Kreis Oberspreewald-Lausitz',
    'Kreis Oder-Spree',
    'Kreis Ostprignitz-Ruppin',
    'Kreis Potsdam-Mittelmark',
    'Kreis Prignitz',
    'Kreis Spree-Neiße',
    'Kreis Teltow-Fläming',
    'Kreis Uckermark',
    'Hansestadt Rostock',
    'Stadt Schwerin',
    'Stadt Chemnitz',
    'Erzgebirgskreis',
    'Stadt Dresden',
    'Kreis Meißen',
    'Stadt Leipzig',
    'Kreis Leipzig',
    'Stadt Dessau-Roßlau',
    'Stadt Halle (Saale)',
    'Stadt Magdeburg',
    'Altmarkkreis Salzwedel',
    'Kreis Anhalt-Bitterfeld',
    'Kreis Börde',
    'Burgenlandkreis',
    'Kreis Jerichower Land',
    'Kreis Mansfeld-Südharz',
    'Saalekreis',
    'Salzlandkreis',
    'Kreis Stendal',
    'Kreis Wittenberg',
    'Stadt Erfurt',
    'Stadt Gera',
    'Stadt Jena',
    'Stadt Suhl',
    'Stadt Weimar',
    'Stadt Eisenach',
    'Kreis Eichsfeld',
    'Kreis Nordhausen',
    'Wartburgkreis',
    'Unstrut-Hainich-Kreis',
    'Kyffhäuserkreis',
    'Kreis Schmalkalden-Meiningen',
    'Kreis Gotha',
    'Kreis Sömmerda',
    'Kreis Hildburghausen',
    'Ilm-Kreis',
    'Kreis Weimarer Land',
    'Kreis Sonneberg',
    'Kreis Saalfeld-Rudolstadt',
    'Saale-Holzland-Kreis',
    'Saale-Orla-Kreis',
    'Kreis Greiz',
    'Kreis Altenburger Land',
];

$sql = "INSERT INTO     wcf1_weather_warning_region
                        (regionName)
        VALUES          (?)";
$statement = WCF::getDB()->prepare($sql);

foreach ($regions as $regionName) {
    $statement->execute([$regionName]);
}
